#pipeline {
 #   agent any
  #  stages {
   #     stage('deploy'){
    #        steps {
     #           sh 'echo DEPLOYING...'
      #          sh 'vagrant up --provision'
       #         sh 'echo DEPLOY STAGE OK'
        #    }
#        }
#    }
#}
pipeline {
  agent any
  stages {
  stage('Stage 1') {
      steps {
        script {
          echo 'Stage 1'
        }
      }
    }
  stage('Stage 2') {
      steps {
        script {
          echo 'Stage 2'
        }
      }
    }
  }
}
